# Generated by Django 5.0.6 on 2025-07-09 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='cpnj',
            new_name='cnpj',
        ),
    ]
