# Generated by Django 5.0.6 on 2025-10-10 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField(blank=True, default=0)),
                ('qtd_entrada', models.IntegerField()),
                ('estoque_minimo', models.IntegerField()),
                ('estoque_maximo', models.IntegerField()),
                ('situacao', models.CharField(choices=[('ativo', 'Ativo'), ('fora_de_linha', 'Fora de linha'), ('ruptura', 'Ruptura'), ('preco_desatualizado', 'Preço desatualizado'), ('consumo_proprio', 'Consumo próprio'), ('nao_comercializado', 'Não comercializado')], default='ativo', max_length=30)),
                ('ref_fabricante', models.CharField(max_length=100)),
                ('cod_embalagem', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('cod_barra', models.CharField(max_length=50)),
                ('apresentacao', models.CharField(max_length=60)),
                ('data_ultima_compra', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('fabricante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.fabricante')),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.grupo')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada de Produto'), ('saida', 'Saída de Produto')], max_length=30)),
                ('quantidade', models.IntegerField()),
                ('data', models.DateField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('fornecedor', models.CharField(blank=True, default='-', max_length=50)),
                ('cliente', models.CharField(blank=True, default='-', max_length=50)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.produto')),
            ],
        ),
    ]
