# Generated by Django 5.2.2 on 2025-06-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='situacao',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('fora_de_linha', 'Fora de linha'), ('ruptura', 'Ruptura'), ('preco_desatualizado', 'Preço desatualizado'), ('consumo_proprio', 'Consumo próprio'), ('nao_comercializado', 'Não comercializado')], default='ativo', max_length=30),
        ),
    ]
