# Generated by Django 5.0.6 on 2025-10-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_tipoentrada_tiposaida'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='tipoEntrada',
            field=models.CharField(blank=True, default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='tipoSaida',
            field=models.CharField(blank=True, default='-', max_length=50),
        ),
    ]
