# Generated by Django 5.0.6 on 2025-07-10 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_alter_produto_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='codigo',
        ),
    ]
