# Generated by Django 5.2.2 on 2025-07-14 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_movimentacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimentacao',
            old_name='observação',
            new_name='observacao',
        ),
    ]
