# Generated by Django 5.2.5 on 2025-10-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_rename_observação_movimentacao_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='fornecedor',
            field=models.TextField(blank=True),
        ),
    ]
