# Generated by Django 5.2.5 on 2025-10-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_movimentacao_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='fornecedor',
            field=models.CharField(blank=True),
        ),
    ]
