# Generated by Django 5.2.5 on 2025-10-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_alter_movimentacao_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='cliente',
            field=models.CharField(blank=True),
        ),
    ]
