# Generated by Django 5.2.5 on 2025-10-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_movimentacao_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='cliente',
            field=models.CharField(blank=True, default='-'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='fornecedor',
            field=models.CharField(blank=True, default='-'),
        ),
    ]
