# Generated by Django 5.2.1 on 2025-05-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_chave_gerenciador'),
    ]

    operations = [
        migrations.AddField(
            model_name='chave_gerenciador',
            name='nome',
            field=models.CharField(default='', max_length=20),
        ),
    ]
