# Generated by Django 5.2.1 on 2025-05-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_chave_gerenciador_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='chave_gerenciador',
            name='chave',
            field=models.CharField(default='', max_length=20),
        ),
    ]
