# Generated by Django 5.2.2 on 2025-08-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='agencia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='conta_corrente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='contato_tel1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='contato_tel2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='contato_tel3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='contato_tel4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='margem_lucro',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='n_banco',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='prazo_entrega',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
