# Generated by Django 5.2.2 on 2025-08-15 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='contasreceber',
            name='forma_pgto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.formapagamento'),
        ),
    ]
