# Generated by Django 5.0.6 on 2025-08-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='insc_estadual',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='insc_municipal',
            field=models.CharField(max_length=10),
        ),
    ]
