# Generated by Django 5.2.2 on 2025-08-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_fornecedor_agencia_fornecedor_conta_corrente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
    ]
