# Generated by Django 5.0.6 on 2025-07-27 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tecnicos', '0002_remove_tecnico_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('unidade', models.CharField(max_length=10)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tecnicos.tecnico')),
            ],
        ),
    ]
