# Generated by Django 5.0.6 on 2025-06-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('titulo', models.CharField(max_length=100)),
                ('data_abertura', models.DateTimeField()),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em andamento'), ('aguardando', 'Aguardando peças'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], max_length=20)),
                ('n_cliente', models.CharField(choices=[('cliente_1', 'Cliente 1'), ('cliente_2', 'Cliente 2'), ('cliente_3', 'Cliente 3'), ('cliente_4', 'Cliente 4')], max_length=50)),
                ('digitador', models.CharField(choices=[('joao', 'João'), ('maria', 'Maria'), ('carlos', 'Carlos'), ('ana', 'Ana')], max_length=50)),
                ('unidade', models.CharField(choices=[('unidade_a', 'Unidade A'), ('unidade_b', 'Unidade B'), ('unidade_c', 'Unidade C'), ('unidade_d', 'Unidade D')], max_length=50)),
                ('segmento', models.CharField(choices=[('eletrico', 'Elétrico'), ('civil', 'Civil'), ('hidraulico', 'Hidráulico'), ('automacao', 'Automação')], max_length=50)),
                ('n_proposta', models.IntegerField()),
                ('n_desenho', models.IntegerField()),
                ('n_art', models.IntegerField()),
                ('solicitante', models.CharField(max_length=100)),
                ('obra_inicio', models.DateTimeField()),
                ('obra_termino', models.DateTimeField()),
                ('obra_nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('municipio', models.CharField(max_length=100)),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='RJ', max_length=2)),
                ('uc_os', models.CharField(max_length=100)),
                ('oc', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='anexos/')),
            ],
        ),
    ]
