# Generated by Django 5.2.2 on 2025-06-27 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_alter_cliente_estado_real'),
        ('ordem_servico', '0002_segmento_status_unidade_alter_ordemservico_segmento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='n_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
    ]
