# Generated by Django 5.0.6 on 2025-06-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_servico', '0005_produtoordemservico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='data_abertura',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='obra_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='obra_termino',
            field=models.DateField(),
        ),
    ]
