# Generated by Django 5.0.6 on 2025-06-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_servico', '0006_alter_ordemservico_data_abertura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoordemservico',
            name='baixa',
            field=models.BooleanField(default=False),
        ),
    ]
