# Generated by Django 5.2.2 on 2025-07-01 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0015_alter_cliente_data_inclusao'),
        ('ordem_servico', '0006_alter_ordemservico_data_abertura_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoordemservico',
            name='baixa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='digitador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='n_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='segmento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordem_servico.segmento'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordem_servico.status'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordem_servico.unidade'),
        ),
    ]
