# Generated by Django 5.0.6 on 2025-07-10 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_servico', '0007_produtoordemservico_baixa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='codigo',
        ),
    ]
