# Generated by Django 5.0.6 on 2025-07-11 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_remove_cliente_codigo'),
        ('ordem_servico', '0008_remove_ordemservico_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='n_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente'),
        ),
    ]
