# Generated by Django 5.0.6 on 2025-07-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_servico', '0010_alter_ordemservico_obra_termino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='obra_termino',
            field=models.DateField(blank=True, null=True),
        ),
    ]
