# Generated by Django 5.0.6 on 2025-07-20 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_servico', '0011_alter_ordemservico_obra_termino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtoordemservico',
            name='baixa',
        ),
    ]
