# Generated by Django 5.0.6 on 2025-07-28 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_servico', '0012_remove_produtoordemservico_baixa'),
        ('servicos', '0002_remove_servico_profissional'),
        ('tecnicos', '0002_remove_tecnico_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoOrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comissao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comissao_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='ordem_servico.ordemservico')),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tecnicos.tecnico')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.servico')),
            ],
        ),
    ]
