# Generated by Django 5.2.2 on 2025-07-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_servico', '0013_servicoordemservico'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicoordemservico',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
