# Generated by Django 5.2.2 on 2025-07-30 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_servico', '0014_servicoordemservico_quantidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaOrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('combustivel', 'Combustível'), ('alimentacao', 'Alimentação'), ('hospedagem', 'Hospedagem'), ('mao-de-obra', 'Mão de obra'), ('sms', 'SMS'), ('consumiveis', 'Consumíveis'), ('comissao', 'Comissão'), ('locacao', 'Locação'), ('outros', 'Outros'), ('materia-prima', 'Matéria Prima'), ('transporte', 'Transporte'), ('equipamento', 'Equipamento')], max_length=20)),
                ('descricao', models.TextField()),
                ('quantidade', models.IntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='ordem_servico.ordemservico')),
            ],
        ),
    ]
