# Generated by Django 5.0.6 on 2025-07-10 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnico',
            name='codigo',
        ),
    ]
