# Generated by Django 5.2.2 on 2025-07-28 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0002_remove_tecnico_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tecnico',
            old_name='prc_comissao',
            new_name='comissao',
        ),
    ]
