# Generated by Django 5.2.1 on 2025-05-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('nome_cliente', models.CharField(max_length=100)),
                ('nome_fantasia', models.CharField(blank=True, max_length=100)),
                ('email1', models.EmailField(max_length=254)),
                ('email2', models.EmailField(blank=True, max_length=254, null=True)),
                ('email3', models.EmailField(blank=True, max_length=254, null=True)),
                ('cnpj_cpf', models.CharField(max_length=18)),
                ('telefone1', models.CharField(blank=True, max_length=20)),
                ('telefone2', models.CharField(blank=True, max_length=20)),
                ('celular1', models.CharField(blank=True, max_length=20)),
                ('celular2', models.CharField(blank=True, max_length=20)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=50)),
                ('inscricao_municipal', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
