# Generated by Django 5.2.1 on 2025-05-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_data_inclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='inscricao_estadual',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='inscricao_municipal',
            field=models.CharField(max_length=50),
        ),
    ]
