# Generated by Django 5.2.1 on 2025-06-03 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_inscricao_estadual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='email3',
        ),
    ]
