# Generated by Django 5.2.1 on 2025-06-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_cliente_atividade_alter_cliente_bairro_real_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='complemento_real',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
