# Generated by Django 5.2.1 on 2025-06-05 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_atividade_segmento_alter_cliente_atividade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='atividade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.atividade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='segmento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.segmento'),
        ),
    ]
