# Generated by Django 5.2.1 on 2025-06-05 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_alter_cliente_atividade_alter_cliente_segmento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='atividade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.atividade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='segmento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.segmento'),
        ),
    ]
