# Generated by Django 5.2.2 on 2025-06-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_alter_cliente_atividade_alter_cliente_segmento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj_cpf',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
