# Generated by Django 5.2.2 on 2025-06-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_alter_cliente_cnpj_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
