# Generated by Django 5.2.2 on 2025-06-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_alter_cliente_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
