# Generated by Django 5.2.2 on 2025-07-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_alter_cliente_estado_real'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_inclusao',
            field=models.DateField(),
        ),
    ]
