# Generated by Django 5.0.6 on 2025-07-10 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0015_alter_cliente_data_inclusao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='codigo',
        ),
    ]
