# Generated by Django 5.2.1 on 2025-06-03 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_atividade_segmento_delete_util_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividade',
            old_name='atividade',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='segmento',
            old_name='segmento',
            new_name='nome',
        ),
    ]
