# Generated by Django 5.2.1 on 2025-06-05 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_atividade_segmento_alter_cliente_atividade_and_more'),
        ('principal', '0003_rename_atividade_atividade_nome_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Atividade',
        ),
        migrations.DeleteModel(
            name='Segmento',
        ),
    ]
